Api integration in Sign Up and sign Page
TamoorKhokhar/LuminogicsFoodClock pull request #4
Opened 2022-08-09 08:43 UTC by TamoorKhokhar

2022-08-10 06:07 UTC, MuhAhs001 commented on src/utils/services/tableDataServices.js
> +    return response;
return only require data it will help you to avoid extra condition in your main components

2022-08-10 06:07 UTC, MuhAhs001 commented on src/utils/services/tableDataServices.js
> +    return response;
again console
return only require data it will help you to avoid extra condition in your main components

2022-08-10 06:07 UTC, MuhAhs001 commented on src/utils/services/tableDataServices.js
> +import { request } from "./common";
Please change your file into meaningfull name

2022-08-10 06:07 UTC, MuhAhs001 commented on src/pages/landingPage.jsx
> +              )}
here the only change is to link
so please add check only for "to" don't repeat code

2022-08-10 06:07 UTC, MuhAhs001 commented on src/pages/authentication/signUp.jsx
> +    console.log(userData);
again console

2022-08-10 06:07 UTC, MuhAhs001 commented on src/pages/authentication/signUp.jsx
> +      }, 3000);
why wait for 3000 ms

2022-08-10 06:07 UTC, MuhAhs001 commented on src/pages/authentication/signUp.jsx
> +      toast("Sign Up Successfully!");
toaster is not required for success because for success it will move to required page

2022-08-10 06:07 UTC, MuhAhs001 commented on src/pages/authentication/signIn.jsx
> +      }, 3000);
why wait for 3000ms

2022-08-10 15:10 UTC, MuneebKhan1996 requested changes

2022-08-10 15:10 UTC, MuneebKhan1996 commented on src/components/button.jsx
> +      {handleOpen}
What is this method doing here? Please explain.

2022-08-10 15:10 UTC, MuneebKhan1996 commented on src/components/teaData.jsx
> +  const user = useSelector((state) => {
const name = useSelector((state) => state?.signIn?.signIn?.userName) || ""
Please simplify it everywhere.

2022-08-10 15:10 UTC, MuneebKhan1996 commented on src/container/tableContainer.js
> +    setTableRowsData(tableData);
if api return true only then you should set that particular data.

2022-08-11 05:26 UTC, MuhAhs001 approved these changes

2022-08-11 05:26 UTC, MuhAhs001 commented on src/utils/services/orderServices.js
> +    if (response?.metadata?.status === "SUCCESS") {
still having console @TamoorKhokhar

2022-08-11 06:47 UTC, merged